# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ['ghc8107', 'ghc924']
        os: [ubuntu-latest, macOS-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    steps:
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io/ https://cache.zw3rk.com/ https://cache.nixos.org/

    - name: Enter devx-shell
      run: nix develop github:input-output-hk/devx#ghc8107-minimal # vs. yvan-sraka/static-closure

    - name: Build
      run: |
        cabal update
        cabal build
